### ISSUE TITLE
Where do I update to use my API Key?

### ISSUE THREAD

**Issue by KnowhereFern** [qmatteoq/outlook-businessmails-openai#1]
Hi! came accross your post on https://techcommunity.microsoft.com/t5/modern-work-app-consult-blog/bringing-openai-into-an-outlook-add-in-a-business-mail-generator/ba-p/3743099

and saw you offered the completed project. If I wanted to use my API key, would I need to build from scratch or is there something I can do to continue using your completed version with my API key?

**Comment by shahshyam** [comment]
https://github.com/qmatteoq/outlook-businessmails-openai/blob/master/src/taskpane/components/App.tsx you lince 35. apiKey: "your-api-key",

**Comment by qmatteoq** [comment]
Thanks @shahshyam for helping :-)

**Comment by shahshyam** [comment]
@qmatteoq You are welcome sir. I have several years of experience in Outlook VSTO /COM add-in development and also working for Outlook web add-ins. If there is any space for my skill. I will help sure.
