### ISSUE TITLE
Errors when launching, Generate Business Email textboxes loose focus on typing, Summarize mail sits on The AI is working

### ISSUE THREAD

**Issue by asheroto** [qmatteoq/outlook-businessmails-openai#5]
Hi there!

I'm excited to get this up and going! I'm an intermediate level developer and have experience with React.

I have been reading this article:
https://techcommunity.microsoft.com/t5/modern-work-app-consult-blog/bringing-openai-into-an-outlook-add-in-a-business-mail-generator/ba-p/3743099

I am having some issues with this though, and I'm wondering if it's due to the node version I have? I'm using LTS version 18.15.0. Latest version of VS Code.

I have changed the OpenAI API key in two spots on App.tsx and one spot on commands.ts.

When I start debugging with VS Code and enable breakpoints on caught/uncaught exceptions, there are a lot of breakpoints. Here's a video...

https://user-images.githubusercontent.com/49938263/229021430-7d605f8c-01d1-4ad1-9da5-58e19638ef82.mp4

If I disable the breakpoints and try to use it, "Summarize mail" lets me type, but gets stuck on "The AI is working". In Generate business mail, when I begin to type in the textboxes, the focus of the pointer is lost. I can click there, but as soon as I begin typing, it looses focus. Video for this...

https://user-images.githubusercontent.com/49938263/229022155-a023752b-00a1-43d7-8d7c-b8ef3e7261a3.mp4

Thank you so much for your work on this and for your time to help debug!

**Comment by raferlekam** [comment]
I've got the same problem

**Comment by qmatteoq** [comment]
I'm really sorry, I didn't get any notification and I missed this issue. Let me take a deeper look, I saw the breakpoint problem on my machine but not the second one.

**Comment by qmatteoq** [comment]
The focus issue should have been fixed by commit 4e2b0be

**Comment by asheroto** [comment]
> I'm really sorry, I didn't get any notification and I missed this issue. Let me take a deeper look, I saw the breakpoint problem on my machine but not the second one.

No problem! Thanks.

> The focus issue should have been fixed by commit [4e2b0be](https://github.com/qmatteoq/outlook-businessmails-openai/commit/4e2b0bebfb0e592512cf3af9acecc2f22e20c64a)

Great, I will try it this weekend and update the issue.

**Comment by asheroto** [comment]
Got it to work, awesome, thanks!

You might consider adding support for a `.env` file so users could specify:
- OpenAI API key
- URL for development/production
- Development/production mode

Like this...

```bash
URL_DEV="https://localhost:3000/"
URL_PROD="https://www.contoso.com/"
OPENAI_API_KEY="abc123"
```

I was going to add it and do a PR, but I tried using the `dotenv` package and the `env-cmd` package but got errors with `fs` and `os`. My node.js skills aren't strong enough to resolve. Not a bug of course, but a feature request. 😊

**Comment by qmatteoq** [comment]
I'm glad the problem is solved! Regarding using the env file to store secrets, I experimented with this approach but it seems it doesn't work with Office add-ins. The process.env object is always empty, even after following the React naming conventions. I'll do a little bit more digging 😊

**Comment by asheroto** [comment]
I found that issue as well. Tried prefixing `REACT_APP_` to environmental variables as _supposedly_ those work in .env but didn't have much luck. I think I was able to get it to work in `webpack.config.js` alone, but not in the actual add-in.

**Comment by asheroto** [comment]
Just found this, might help. So... a `config.json` file might suffice if `.env` is not supported.

https://stackoverflow.com/questions/70103368/set-value-of-a-variable-depending-on-build-for-an-office-addin-conditional-var

Thanks again for building this add-in.
